# Generated by Django 2.2.7 on 2019-11-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searcheddate',
            name='month',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searcheddate',
            name='date',
            field=models.CharField(max_length=3),
        ),
    ]
