# Generated by Django 2.2.7 on 2019-11-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20191125_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Range_rank', models.CharField(max_length=30)),
                ('showRange', models.CharField(max_length=30)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('poster_url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=20)),
                ('movie_code', models.IntegerField()),
                ('naver_movie_url', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
